DROP DATABASE IF EXISTS "topicosii";

DROP ROLE IF EXISTS topicosii;

CREATE ROLE topicosii LOGIN
ENCRYPTED PASSWORD 'b3a7bff724584262b6340aa97263eda9'
SUPERUSER INHERIT CREATEDB CREATEROLE REPLICATION;

CREATE DATABASE "topicosii"
WITH OWNER = topicos
ENCODING = 'UTF8'
TABLESPACE = pg_default
CONNECTION LIMIT = -1;